# peer_address here should be dynamically generated (see: https://github.com/bloxbean/yaci-devkit/issues/87)
# this comes from yaci-devkit
[upstream]
peer_address = "localhost:3001"
network_magic = 42 # comes from the shelley genesis block
is_testnet = true
 
[storage]
path = "data"
max_wal_history = 10000

[genesis]
# note: filled programmatically

[sync]
pull_batch_size = 100
 
[submit]
prune_height = 200
 
[serve.grpc]
listen_address = "[::]:50051"

[serve.ouroboros]
listen_path = "dolos.socket"
magic = 42
 
[relay]
listen_address = "[::]:30031"
magic = 42

[logging]
max_level = "INFO"
include_tokio = false
include_pallas = false
include_grpc = true
